import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "CareMind - The mind can control your operations",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: '--font-inter',
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
